services:
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: amd64/mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=marcelo
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: