services:
  loadbalancer:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
      - app3
      - app4
    networks:
      - app-network
  app1:
    image: nginx:latest
    volumes:
      - ./html/app1.html:/usr/share/nginx/html/index.html:ro
    networks:
      - app-network
  app2:
    image: nginx:latest
    volumes:
      - ./html/app2.html:/usr/share/nginx/html/index.html:ro
    networks:
      - app-network
  app3:
    image: nginx:latest
    volumes:
      - ./html/app3.html:/usr/share/nginx/html/index.html:ro
    networks:
      - app-network
  app4:
    image: nginx:latest
    volumes:
      - ./html/app4.html:/usr/share/nginx/html/index.html:ro
    networks:
      - app-network
networks:
  app-network: